# Generated by Django 5.2.18 on 2026-10-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Organization domain',
                'verbose_name_plural': 'Organization domains',
                'ordering': ['-is_primary', 'hostname'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='one_primary_domain_per_organization')],
            },
        ),
    ]
