# Generated by Django 5.2.18 on 2026-10-09 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizationdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='display_name',
            field=models.CharField(blank=True, help_text='Shown in the navbar, page titles and emails. Defaults to the organisation name.', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_from_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='org_favicons/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'svg'])]),
        ),
        migrations.AddField(
            model_name='organization',
            name='navbar_style',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('primary', 'Primary colour')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use a hex colour like #0d6efd.')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
