# Generated by Django 5.2.18 on 2026-10-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='terminology',
            field=models.JSONField(blank=True, default=dict, help_text='Words this organisation uses instead of the EOS defaults, e.g. {"rock": "Priority", "rocks": "Priorities"}. Only overrides are stored.'),
        ),
    ]
