# Generated by Django 5.2.17 on 2026-09-09 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='What does "done" look like? Make it specific and measurable.')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('year', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('off_track', 'Off Track'), ('complete', 'Complete'), ('dropped', 'Dropped')], default='on_track', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rocks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_rocks', to=settings.AUTH_USER_MODEL)),
                ('parent_rock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_rocks', to='rocks.rock')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocks', to='accounts.team')),
            ],
            options={
                'verbose_name': 'Rock',
                'verbose_name_plural': 'Rocks',
                'ordering': ['team__name', 'owner__first_name', 'owner__username', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RockDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Why does this Rock depend on the other?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depends_on_rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='rocks.rock')),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='rocks.rock')),
            ],
            options={
                'verbose_name': 'Rock Dependency',
                'verbose_name_plural': 'Rock Dependencies',
                'unique_together': {('rock', 'depends_on_rock')},
            },
        ),
    ]
