# Generated by Django 5.2.17 on 2026-09-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='rocks.rock')),
            ],
            options={
                'verbose_name': 'Rock Milestone',
                'verbose_name_plural': 'Rock Milestones',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
