# Generated by Django 5.2.17 on 2026-09-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0002_add_rock_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockmilestone',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
