# Generated by Django 5.2.17 on 2026-09-18 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0003_milestone_add_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RockCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(choices=[('on_track', 'On Track'), ('off_track', 'Off Track')], default='on_track', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rock_checkins', to=settings.AUTH_USER_MODEL)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='rocks.rock')),
            ],
            options={
                'verbose_name': 'Rock Check-in',
                'verbose_name_plural': 'Rock Check-ins',
                'ordering': ['-created_at'],
            },
        ),
    ]
