# Generated by Django 5.2.17 on 2026-09-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vto', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='VTOCoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('vto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='vto.vto')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VTOSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('core_focus_purpose', 'Core Focus — Purpose/Passion/Cause'), ('core_focus_niche', 'Core Focus — Niche'), ('ten_year_target', '10-Year Target'), ('target_market', 'Marketing — Target Market'), ('three_uniques', 'Marketing — Three Uniques'), ('proven_process', 'Marketing — Proven Process'), ('guarantee', 'Marketing — Guarantee'), ('three_year_picture', '3-Year Picture'), ('three_year_goals', '3-Year Goals'), ('one_year_revenue', '1-Year Plan — Revenue Target'), ('one_year_profit', '1-Year Plan — Profit Target'), ('one_year_goals', '1-Year Plan — Critical Goals')], max_length=40)),
                ('content', models.TextField(blank=True)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vto_edits', to=settings.AUTH_USER_MODEL)),
                ('vto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='vto.vto')),
            ],
            options={
                'unique_together': {('vto', 'key')},
            },
        ),
        migrations.CreateModel(
            name='VTOSectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('edited_at', models.DateTimeField()),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vto_history', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vto.vtosection')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
