# Generated by Django 5.2.17 on 2026-09-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vto', '0002_migrate_three_uniques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtosection',
            name='key',
            field=models.CharField(choices=[('core_focus_purpose', 'Core Focus — Purpose/Passion/Cause'), ('core_focus_niche', 'Core Focus — Niche'), ('ten_year_target', '10-Year Target'), ('target_market', 'Marketing — Target Market'), ('three_uniques_1', 'Marketing — Three Uniques — 1'), ('three_uniques_2', 'Marketing — Three Uniques — 2'), ('three_uniques_3', 'Marketing — Three Uniques — 3'), ('proven_process', 'Marketing — Proven Process'), ('guarantee', 'Marketing — Guarantee'), ('three_year_picture', '3-Year Picture'), ('three_year_goals', '3-Year Goals'), ('one_year_revenue', '1-Year Plan — Revenue Target'), ('one_year_profit', '1-Year Plan — Profit Target'), ('one_year_goals', '1-Year Plan — Critical Goals')], max_length=40),
        ),
    ]
