# Generated by Django 5.2.17 on 2026-09-09 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('rocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('issue_type', models.CharField(choices=[('short_term', 'Short-term'), ('long_term', 'Long-term')], default='short_term', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_ids', 'In IDS'), ('resolved', 'Resolved'), ('dropped', 'Dropped')], default='open', max_length=20)),
                ('target_quarter', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], null=True)),
                ('target_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL)),
                ('delegated_to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_issues', to='accounts.team')),
                ('linked_rocks', models.ManyToManyField(blank=True, related_name='linked_issues', to='rocks.rock')),
                ('originating_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originated_issues', to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('delegated', 'Delegated'), ('recalled', 'Recalled'), ('status_changed', 'Status Changed'), ('rock_linked', 'Rock Linked'), ('rock_unlinked', 'Rock Unlinked'), ('comment', 'Comment'), ('resolved', 'Resolved'), ('dropped', 'Dropped')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_activities', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='issues.issue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
