# Generated by Django 5.2.17 on 2026-09-09 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='accounts.team')),
            ],
            options={
                'ordering': ['team__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScorecardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metric_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('percentage', 'Percentage')], default='integer', max_length=20)),
                ('goal_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('goal_direction', models.CharField(choices=[('above', 'At or above goal (higher is better)'), ('below', 'At or below goal (lower is better)'), ('equal', 'Equal to goal')], default='above', max_length=10)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scorecard_metrics', to=settings.AUTH_USER_MODEL)),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='scorecards.scorecard')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScorecardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('on_track', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecard_entries', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scorecards.scorecardmetric')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('metric', 'period_start')},
            },
        ),
    ]
