# Generated by Django 5.2.17 on 2026-09-20 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdue_todo_digest', models.BooleanField(default=True, help_text='Daily email listing your overdue To-Dos.')),
                ('meeting_reminders', models.BooleanField(default=True, help_text="Email reminder on your team's Level 10 Meeting day.")),
                ('rock_off_track_alerts', models.BooleanField(default=True, help_text='Email when one of your Rocks is marked off track.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
